mod builder;

// Metadata based on Adaptive Metadata Tree
// https://docs.google.com/document/d/1k4x8utgh41Sn1tr98eynDKCWq035SV_f75rtNHcerVw
use crate::expressions::Scalar;
use crate::schema::{derive_macro_utils::ToDataType, DataType};
use crate::{DeltaResult, Error};
use bytes::Bytes;
use delta_kernel_derive::{IntoEngineData, ToSchema};
use std::str::FromStr;

/// Type of content stored by the manifest entry
#[allow(dead_code)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub(crate) enum DataContentType {
    Data = 0,
    PositionDeletes = 1,
    EqualityDeletes = 2,
    // Types below are only allowed in the root
    DataManifest = 3,
    DeleteManifest = 4,
    ManifestDV = 5,
}

// ToDataType implementations for enums
impl ToDataType for DataContentType {
    fn to_data_type() -> DataType {
        DataType::INTEGER
    }
}

impl From<DataContentType> for Scalar {
    fn from(value: DataContentType) -> Self {
        Scalar::Integer(value as i32)
    }
}

/// Format of this data.
#[allow(dead_code)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub(crate) enum DataFileFormat {
    /// Parquet file format: <https://parquet.apache.org/>
    Parquet,
    /// Puffin file format: <https://iceberg.apache.org/puffin-spec/>
    Puffin,
}

impl FromStr for DataFileFormat {
    type Err = Error;

    fn from_str(s: &str) -> DeltaResult<Self> {
        match s.to_lowercase().as_str() {
            "parquet" => Ok(Self::Parquet),
            "puffin" => Ok(Self::Puffin),
            _ => Err(Error::internal_error(format!(
                "Unsupported data file format: {}",
                s
            ))),
        }
    }
}

impl std::fmt::Display for DataFileFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DataFileFormat::Parquet => write!(f, "parquet"),
            DataFileFormat::Puffin => write!(f, "puffin"),
        }
    }
}

impl ToDataType for DataFileFormat {
    fn to_data_type() -> DataType {
        DataType::STRING
    }
}

impl From<DataFileFormat> for Scalar {
    fn from(value: DataFileFormat) -> Self {
        Scalar::String(value.to_string())
    }
}

#[allow(dead_code)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub(crate) enum TrackingStatus {
    Existed = 0,
    Added = 1,
    Deleted = 2,
}

impl ToDataType for TrackingStatus {
    fn to_data_type() -> DataType {
        DataType::INTEGER
    }
}

impl From<TrackingStatus> for Scalar {
    fn from(value: TrackingStatus) -> Self {
        Scalar::Integer(value as i32)
    }
}

#[allow(dead_code)]
#[derive(Debug, ToSchema, IntoEngineData)]
pub(crate) struct TrackingInfo {
    status: TrackingStatus,

    /// Snapshot ID where the file was added, or deleted if status is 2. Inherited when null.
    snapshot_id: Option<i64>,

    /// Data sequence number of the file. Inherited in when null and status is 1 (added).
    /// Must be equal to file_sequence_number if content_type is {Data,Delete}Manifest.
    sequence_number: Option<i64>,

    /// File sequence number indicating when the file was added. Inherited when null and status is added.
    /// Must be equal to sequence_number if content_type is {Data,Delete}Manifest.
    file_sequence_number: Option<i64>,

    /// The _row_id for the first row in the data file if content_type is Data.
    /// If content_type is DataManifest, this is the starting _row_id to assign to rows added by ADDED data files.
    first_row_id: Option<i64>,
}

impl From<TrackingInfo> for Scalar {
    fn from(value: TrackingInfo) -> Self {
        use crate::expressions::StructData;
        use crate::schema::ToSchema;

        let fields = TrackingInfo::to_schema().into_fields().collect();
        let values = vec![
            value.status.into(),
            value.snapshot_id.into(),
            value.sequence_number.into(),
            value.file_sequence_number.into(),
            value.first_row_id.into(),
        ];

        // SAFETY: Fields are generated by ToSchema derive macro and values are constructed
        // to match exactly in count, order, type, and nullability.
        Scalar::Struct(StructData::new_unchecked(fields, values))
    }
}

#[allow(dead_code)]
#[derive(Debug, ToSchema, IntoEngineData)]
pub(crate) struct DeletionVector {
    /// The offset in the file where the content starts.
    offset: Option<i64>,

    /// The length of a referenced content stored in the file; required if content_offset is present.
    /// The number of 32-bit Roaring bitmaps, serialized as 8 bytes, little-endian
    ///  - For each 32-bit Roaring bitmap, ordered by unsigned comparison of the 32-bit keys:
    ///     - The key stored as 4 bytes, little-endian
    ///     - A 32-bit Roaring bitmap
    size_in_bytes: Option<i64>,

    /// Serialized bitmap for inline DVs.
    inline_content: Option<Bytes>,
}

impl From<DeletionVector> for Scalar {
    fn from(value: DeletionVector) -> Self {
        use crate::expressions::StructData;
        use crate::schema::ToSchema;

        let fields = DeletionVector::to_schema().into_fields().collect();
        let values = vec![
            value.offset.into(),
            value.size_in_bytes.into(),
            value.inline_content.into(),
        ];

        // SAFETY: Fields are generated by ToSchema derive macro and values are constructed
        // to match exactly in count, order, type, and nullability.
        Scalar::Struct(StructData::new_unchecked(fields, values))
    }
}

#[allow(dead_code)]
#[derive(Debug, ToSchema, IntoEngineData)]
pub(crate) struct ContentStats {
    // https://docs.google.com/document/d/1uvbrwwAJW2TgsnoaIcwAFpjbhHkBUL5wY_24nKgtt9I/
    // Today this is static and still empty. In the future to be generated based on the schema
}

impl From<ContentStats> for Scalar {
    fn from(_value: ContentStats) -> Self {
        use crate::expressions::StructData;
        use crate::schema::ToSchema;

        let fields = ContentStats::to_schema().into_fields().collect();
        let values = vec![];

        // SAFETY: Fields are generated by ToSchema derive macro and values are constructed
        // to match exactly in count, order, type, and nullability.
        Scalar::Struct(StructData::new_unchecked(fields, values))
    }
}

#[allow(dead_code)]
#[derive(Debug, ToSchema, IntoEngineData)]
pub(crate) struct ManifestStats {
    added_files_count: i64,
    existing_files_count: i64,
    deletes_files_count: i64,

    added_rows_count: i64,
    existing_rows_count: i64,
    delete_rows_count: i64,

    min_sequence_number: i64,
}

impl From<ManifestStats> for Scalar {
    fn from(value: ManifestStats) -> Self {
        use crate::expressions::StructData;
        use crate::schema::ToSchema;

        let fields = ManifestStats::to_schema().into_fields().collect();
        let values = vec![
            value.added_files_count.into(),
            value.existing_files_count.into(),
            value.deletes_files_count.into(),
            value.added_rows_count.into(),
            value.existing_rows_count.into(),
            value.delete_rows_count.into(),
            value.min_sequence_number.into(),
        ];

        // SAFETY: Fields are generated by ToSchema derive macro and values are constructed
        // to match exactly in count, order, type, and nullability.
        Scalar::Struct(StructData::new_unchecked(fields, values))
    }
}

#[allow(dead_code)]
#[derive(Debug, ToSchema)]
pub(crate) struct MetadataEntry {
    /// Type of content stored by the entry.
    /// DataManifest, DeleteManifest or ManifestDV can only be defined in the root manifest.
    content_type: DataContentType,

    /// Optional if content_type is 5 and deletion_vector.inline_content is not null, required otherwise
    location: Option<String>,

    /// avro, orc, parquet or puffin
    file_format: DataFileFormat,

    tracking_info: TrackingInfo,

    /// Must be defined if content_type is Positional Deletes or ManifestDV.
    deletion_vector: Option<DeletionVector>,

    /// ID of partition spec used to write manifest or data/delete files.
    partition_spec_id: i64,

    /// ID representing sort order for this file. Can only be set if content_type is Data.
    sort_order_id: i64,

    /// Number of records in this file, or the cardinality of a deletion vector
    record_count: i64,

    /// Total file size in bytes. Must be defined if location is defined
    file_size_in_bytes: i64,

    /// The column metrics
    /// https://docs.google.com/document/d/1uvbrwwAJW2TgsnoaIcwAFpjbhHkBUL5wY_24nKgtt9I/
    content_stats: Option<ContentStats>,

    /// Must be set if content_type is {Data,Delete}Manifest, otherwise null.
    manifest_stats: Option<ManifestStats>,

    /// Location of affiliated data manifest if content_type is DeleteManifest or null if delete manifest is unaffiliated.
    referenced_file: Option<String>,

    /// Not used by Delta today
    /// Implementation-specific key metadata for encryption
    key_metadata: Option<Bytes>,

    /// Not used by Delta today
    /// Split offsets for the data file. For example, all row group offsets in a Parquet file. Must be sorted ascending
    split_offsets: Option<Vec<i64>>,

    /// Not used by Delta today
    /// Field ids used to determine row equality in equality delete files.
    /// Required when content is EqualityDeletes and must be null otherwise.
    /// Fields with ids listed in this column must be present in the delete file
    equality_ids: Option<Vec<i32>>,
}

impl crate::IntoEngineData for MetadataEntry {
    fn into_engine_data(
        self,
        schema: crate::schema::SchemaRef,
        engine: &dyn crate::Engine,
    ) -> DeltaResult<Box<dyn crate::EngineData>> {
        use crate::expressions::ArrayData;
        use crate::schema::{ArrayType, DataType, ToSchema};
        use crate::EvaluationHandlerExtension as _;

        // Helper to convert Option<Vec<T>> to Scalar
        fn vec_to_scalar<T>(vec: Option<Vec<T>>, element_type: DataType) -> DeltaResult<Scalar>
        where
            T: Into<Scalar> + crate::schema::derive_macro_utils::ToDataType,
        {
            match vec {
                Some(v) => {
                    let array_type = ArrayType::new(element_type, false);
                    let array_data = ArrayData::try_new(array_type, v)?;
                    Ok(Scalar::Array(array_data))
                }
                None => Ok(Scalar::Null(DataType::Array(Box::new(ArrayType::new(
                    element_type,
                    false,
                ))))),
            }
        }

        let values = [
            Scalar::from(self.content_type),
            Scalar::from(self.location),
            Scalar::from(self.file_format),
            Scalar::from(self.tracking_info),
            match self.deletion_vector {
                Some(dv) => Scalar::from(dv),
                None => Scalar::Null(DeletionVector::to_schema().into()),
            },
            Scalar::from(self.partition_spec_id),
            Scalar::from(self.sort_order_id),
            Scalar::from(self.record_count),
            Scalar::from(self.file_size_in_bytes),
            match self.content_stats {
                Some(cs) => Scalar::from(cs),
                None => Scalar::Null(ContentStats::to_schema().into()),
            },
            match self.manifest_stats {
                Some(ms) => Scalar::from(ms),
                None => Scalar::Null(ManifestStats::to_schema().into()),
            },
            Scalar::from(self.referenced_file),
            Scalar::from(self.key_metadata),
            vec_to_scalar(self.split_offsets, DataType::LONG)?,
            vec_to_scalar(self.equality_ids, DataType::INTEGER)?,
        ];

        let evaluator = engine.evaluation_handler();
        evaluator.create_one(schema, &values)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Note: Full integration test for MetadataEntry::into_engine_data is not included here
    // because it requires complex setup with nested structs. The implementation is complete
    // and can be tested in integration tests with actual data.

    #[test]
    fn test_enum_to_scalar_conversions() {
        // Test DataContentType conversion
        let content_type = DataContentType::Data;
        let scalar: Scalar = content_type.into();
        assert!(matches!(scalar, Scalar::Integer(0)));

        // Test DataFileFormat conversion
        let file_format = DataFileFormat::Parquet;
        let scalar: Scalar = file_format.into();
        assert!(matches!(scalar, Scalar::String(ref s) if s == "parquet"));

        // Test TrackingStatus conversion
        let status = TrackingStatus::Added;
        let scalar: Scalar = status.into();
        assert!(matches!(scalar, Scalar::Integer(1)));
    }

    #[test]
    fn test_bytes_to_scalar_conversion() {
        let bytes = Bytes::from(vec![1, 2, 3, 4]);
        let scalar: Scalar = bytes.into();
        assert!(matches!(scalar, Scalar::Binary(ref v) if v == &vec![1, 2, 3, 4]));
    }
}
